# Generated by Django 3.1.13 on 2021-10-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20211020_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='hour',
            field=models.TimeField(verbose_name='Hour'),
        ),
    ]
