# Generated by Django 3.1.13 on 2021-12-17 11:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brewery',
            fields=[
                ('legacy_id', models.IntegerField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=255)),
                ('filepath', models.CharField(max_length=255)),
                ('descript', models.TextField()),
                ('last_mod', models.DateTimeField(auto_now_add=True, verbose_name='')),
            ],
            options={
                'verbose_name': 'Brewery',
                'verbose_name_plural': 'Breweries',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('legacy_id', models.IntegerField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.RemoveField(
            model_name='beer',
            name='add_user',
        ),
        migrations.RemoveField(
            model_name='beer',
            name='brewery_id',
        ),
        migrations.RemoveField(
            model_name='beer',
            name='cat_id',
        ),
        migrations.RemoveField(
            model_name='beer',
            name='style_id',
        ),
        migrations.AddField(
            model_name='beer',
            name='legacy_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beer',
            name='abv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beer',
            name='descript',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beer',
            name='filepath',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='beer',
            name='ibu',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beer',
            name='last_mod',
            field=models.DateTimeField(auto_now_add=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='beer',
            name='srm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beer',
            name='upc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('legacy_id', models.IntegerField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beers.category')),
            ],
        ),
        migrations.CreateModel(
            name='BreweryLocation',
            fields=[
                ('legacy_id', models.IntegerField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy', models.CharField(blank=True, max_length=50, null=True, verbose_name='Accuracy')),
                ('brewery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beers.brewery')),
            ],
        ),
        migrations.AddField(
            model_name='beer',
            name='brewery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beers.brewery'),
        ),
        migrations.AddField(
            model_name='beer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beers.category'),
        ),
        migrations.AddField(
            model_name='beer',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beers.style'),
        ),
    ]
