# Generated by Django 3.1.13 on 2021-12-17 13:02

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0002_auto_20211217_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
    ]
