# Generated by Django 3.1.13 on 2021-12-17 13:24

from django.db import migrations
from django.contrib.postgres.aggregates import StringAgg

from django.contrib.postgres.search import SearchVector


def compute_search_vector(apps, schema_editor):
    Beer = apps.get_model("beers", "Beer")
    Beer.objects.update(search_vector=SearchVector('name', "descript"))


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0003_beer_search_vector'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER search_vector_trigger
            BEFORE INSERT OR UPDATE OF name, descript, search_vector
            ON beers
            FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger(
                search_vector, 'pg_catalog.english', name, descript
            );
            UPDATE beers SET search_vector = NULL;
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS search_vector_trigger
            ON beers;
            """,
        ),
        migrations.RunPython(
            compute_search_vector, reverse_code=migrations.RunPython.noop
        ),
    ]