# Generated by Django 3.1.13 on 2021-12-21 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0005_auto_20211221_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beer',
            old_name='user',
            new_name='added_by',
        ),
    ]
